/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#b9ccb5",
        "outline": "#6b7c68",
        "on-tertiary-fixed": "#370e00",
        "on-surface-variant": "#3b4b39",
        "tertiary-container": "#ffd4c5",
        "on-tertiary-container": "#ac3b00",
        "secondary": "#575d78",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed-dim": "#ffb59a",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#006e24",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "primary": "#006e24",
        "tertiary-fixed": "#ffdbce",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#bfc5e4",
        "on-primary-fixed": "#002106",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#5b617d",
        "surface": "#f8f9fa",
        "inverse-primary": "#00e554",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#00ff5f",
        "surface-variant": "#e1e3e4",
        "error": "#ba1a1a",
        "on-primary-container": "#007125",
        "primary-fixed-dim": "#00e554",
        "surface-dim": "#d9dadb",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "on-primary-fixed-variant": "#005319",
        "inverse-surface": "#2e3132",
        "secondary-container": "#d8defe",
        "on-tertiary-fixed-variant": "#802a00",
        "on-secondary-fixed-variant": "#3f465f",
        "on-secondary-fixed": "#141a32",
        "primary-fixed": "#6dff7f",
        "tertiary": "#a73a00",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed": "#dce1ff"
      },
    },
  },
  plugins: [],
}
